[package]
name = "bookstore"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.0", features = ["full"]}
sqlx = { version = "0.6", features = ["postgress", "runtime-tokio-rustls"] }
